// lib/firebase_options.dart
// This is a placeholder. In a real project, this would be generated by the FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62yATNnqEno8Gxv3Pq6j_tKIVFDWy9TU',
    appId: '1:754505389939:android:87b988a547a88b62755706',
    messagingSenderId: '754505389939',
    projectId: 'jobnest-90c5b',
    storageBucket: 'jobnest-90c5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApNDtqaNNJ8FM7_YW0MieLGH02vUiSB_Y',
    appId: '1:754505389939:ios:38fb69524e900d7e755706',
    messagingSenderId: '754505389939',
    projectId: 'jobnest-90c5b',
    storageBucket: 'jobnest-90c5b.firebasestorage.app',
    androidClientId: '754505389939-5ouq7rh1cjrrs76v3bq9j5ht6do7irbv.apps.googleusercontent.com',
    iosClientId: '754505389939-s56f7mkeqe29c33s9rihg72b1goghvhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobnest',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoJjw4O2jm2_1f84KikzCy5oyAeGaO6ws',
    appId: '1:754505389939:web:a1692e9f1933103b755706',
    messagingSenderId: '754505389939',
    projectId: 'jobnest-90c5b',
    authDomain: 'jobnest-90c5b.firebaseapp.com',
    storageBucket: 'jobnest-90c5b.firebasestorage.app',
    measurementId: 'G-QGC5JKD8DY',
  );

}