// lib/firebase_options.dart
// This is a placeholder. In a real project, this would be generated by the FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB62yATNnqEno8Gxv3Pq6j_tKIVFDWy9TU',
    appId: '1:754505389939:android:87b988a547a88b62755706',
    messagingSenderId: '754505389939',
    projectId: 'jobnest-90c5b',
    storageBucket: 'jobnest-90c5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApNDtqaNNJ8FM7_YW0MieLGH02vUiSB_Y',
    appId: '1:754505389939:ios:bcbca6d1774ff290755706',
    messagingSenderId: '754505389939',
    projectId: 'jobnest-90c5b',
    storageBucket: 'jobnest-90c5b.firebasestorage.app',
    iosBundleId: 'com.shazaib.jobnes',
  );

}